### ISSUE TITLE
CommandInjector.dll Windows 10 BL2 crash

### ISSUE THREAD

**Issue by RobertVorback** [c0dycode/BL-CommandInjector#1]
If I try to start Borderlands 2 with CommandInjector.dll in the
C:\Program Files (x86)\Steam\steamapps\common\Borderlands 2\Binaries\Win32\Plugins
folder Borderlands 2 will not start, after pressing Play in the launcher the
splash image appears briefly and then nothing furthur happens. There are no error messages. It seems that Windows 10 may be blocking this file
in some way.

**Comment by c0dycode** [comment]
You need to update the file.
See here for more information https://github.com/c0dycode/BL-CommandInjector#borderlands-uhd-update-4k-texture-update

**Comment by RobertVorback** [comment]
I replaced the dll with CommandInjector-UHD.dll
and Borderlands 2 now starts as expected and Borderlands Commander
runs also without a problem, thank you for a quick response and a simple fix
