### ISSUE TITLE
No system tray icon

### ISSUE THREAD

**Issue by hemry64** [c0dycode/BL-CommandInjector#3]
The commander itself seems to be running fine, the text at the top when you open the exe is all green and Test messages go through. I just don't have a system tray Icon so I'm unable to use any hotkeys.

**Comment by c0dycode** [comment]
What you're using is the Example Application. NOT Borderlands Commander. That's a separate tool by mopioid.

**Comment by hemry64** [comment]
Oh wow, I see what I missed here. Sorry for the mix-up, Thank you for helping me realize the problem!
